[project]
name = "llm-ollama"
version = "0.17.1"
description = "LLM plugin providing access to models running on an Ollama server"
readme = "README.md"
requires-python = ">=3.10"
license = "Apache-2.0"
authors = [{ name = "Sergey Alexandrov" }]
dependencies = ["llm>=0.33", "ollama>=0.6.0", "pydantic>=2"]

[project.urls]
CI = "https://github.com/taketwo/llm-ollama/actions"
Changelog = "https://github.com/taketwo/llm-ollama/releases"
Homepage = "https://github.com/taketwo/llm-ollama"
Issues = "https://github.com/taketwo/llm-ollama/issues"

[project.entry-points.llm]
ollama = "llm_ollama"

[project.optional-dependencies]
lint = ["ruff", "ty"]
test = ["pytest", "pytest-asyncio", "pytest-cov", "pytest-mock"]

[dependency-groups]
dev = ["typing-extensions>=4.15.0"]

[tool.setuptools.packages.find]
include = ["llm_ollama*"]
